News/views.py
from flask import render_template
import feedparser
from flask import Blueprint
from datetime import datetime

news_blueprint = Blueprint('news', __name__, template_folder='templates/features')


@news_blueprint.route('/features/news', methods=['get'])
def news():
    feed = feedparser.parse('https://www.england.nhs.uk/feed/')
    articles = feed.entries[:10]

    for article in articles:
        # Parse the date string
        published_datetime = datetime.strptime(article.published, '%a, %d %b %Y %H:%M:%S %z')
        # Format the date string without the timezone offset
        article.published = published_datetime.strftime('%a, %d %b %Y %H:%M:%S')

    return render_template('features/news.html', articles=articles)

SearchDiseases/views.py
"""
Search Disease Views

This file defines a Flask blueprint for handling the search functionality for
diseases and conditions, allowing users to search the NHS website and retrieve
and view relevant data.
"""


from flask import render_template, request, Blueprint
from SearchDiseases.search import NHSWebsiteCrawler
import re


search_blueprint = Blueprint('search', __name__, template_folder='templates/features')


@search_blueprint.route('/search_disease', methods=['GET', 'POST'])
def search_disease():
    """
    Handles the search functionality for diseases.

    Returns:
        string: The rendered HTML template with search results.

    Notes:
        - If the request method is 'POST', the search term is extracted from the form data.
        - An instance of NHSWebsiteCrawler is created to search and retrieve data from the NHS website.
        - The search term is used to search the NHS website.
        - If a match is found, the data related to the search term is retrieved.
        - The search results are rendered in the 'features/search.html' template.
    """
    if request.method == 'POST':
        search_term = request.form['search_term'].strip()

        if not search_term.strip():
            return render_template('features/search.html',
                                   error_message="Please enter a search term.")
        if search_term.isdigit():
            return render_template('features/search.html',
                                   error_message="Please enter a valid search term.")

        #has to include only letters spaces and numbers
        if not re.match(r'^[a-zA-Z\s]*[a-zA-Z][a-zA-Z0-9\s]*$', search_term):
            return render_template('features/search.html',
                                   error_message="Please enter a valid search term.")

        url = 'https://www.nhs.uk/conditions/'
        nhs = NHSWebsiteCrawler(url)

        is_successful, result = nhs.search_website(search_term)

        if is_successful:
            result = nhs.retrieve_data(search_term)

        return render_template('features/search.html',
                               search_term=search_term,
                               result=result,
                               is_successful=is_successful)

    return render_template('features/search.html')

templates/503.html
{% extends "base.html" %}

{% block content %}

    <!--503 - Service Unavailable Error-->
    <div class="error-message">
        <div>
            <h2 class="title is-2">Service unavailable</h2>
            <p>Server is currently unavailable to handle your request</p>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <script src="/static/scripts/scripts.js" defer></script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="author" content="Alexander Freeman">
  <meta name="description" content="website to provide health information for the older generation">
  <meta name="keywords" content="health, ageing, fitness, nutrition">
  <meta name="width" content="device-width">
  <meta name="height" content="device-height">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/static/css/main.css"/>
  <title>Healthy Ageing Plans</title>
  <link rel="icon" href="/static/resources/logo.svg"/>
</head>

<nav class="full-width">
  <div class="nav">
    <img src="/static/resources/logo.svg" alt="Organisation Logo" class="logo">
    <a href="{{ url_for('index') }}" class="title nav-hover"><h2>Healthy Ageing Plans</h2></a>
    <ul class="nav-desktop">
      <li><a href="{{ url_for('index') }}" class="link nav-hover">Home</a></li>
      <li><a href="{{ url_for('news.news') }}" class="link nav-hover">News</a></li>
      <li><a href="{{ url_for('fitness_advice') }}" class="link nav-hover">Fitness Advice</a></li>
      <li><a href="{{ url_for('nutrition_advice') }}" class="link nav-hover">Nutrition Advice</a></li>
      <li class="dropdown">
        <a href="#" class="link nav-hover">Customised Plan</a>
        <ul class="dropdown-list">
          <li><a href="{{ url_for('meal.meal_plan') }}" class="link nav-hover">Create Meal Plan</a></li>
          <li><a href="{{ url_for('fitness.fitness_plan') }}" class="link nav-hover">Create Fitness Plan</a></li>
          <li><a href="{{ url_for('calorie.calories') }}" class="link nav-hover">Calculate Daily Calories</a></li>
        </ul>
        <div class="dropdown-icon"></div>
      </li>
    </ul>
    <form class="search-bar" method="POST" action="{{ url_for('search.search_disease') }}">
        <input type="text" name="search_term" placeholder="Search Disease...">
    </form>
    <div class="menu-icon">
      <span class="one"></span>
      <span class="two"></span>
    </div>
  </div>
  <div id="nav-mobile" class="nav-mobile">
    <ul>
      <li>
        <form class="search-bar-mobile" method="POST" action="{{url_for('search.search_disease')}}"><input type="text" name="search_term" placeholder="Search Disease..." formaction="{{ url_for('search.search_disease') }}"></form>
      </li>
      <li><a href="{{ url_for('index') }}" class="link nav-hover">Home</a></li>
      <li><a href="{{ url_for('news.news') }}" class="link nav-hover">News</a></li>
      <li><a href="{{ url_for('fitness_advice') }}" class="link nav-hover">Fitness Advice</a></li>
      <li><a href="{{ url_for('nutrition_advice') }}" class="link nav-hover">Nutrition Advice</a></li>
      <li><a href="{{ url_for('meal.meal_plan') }}" class="link nav-hover">Create Meal Plan</a></li>
      <li><a href="{{ url_for('fitness.fitness_plan') }}" class="link nav-hover">Create Fitness Plan</a></li>
      <li><a href="{{ url_for('calorie.calories') }}" class="link nav-hover">Calculate Daily Calories</a></li>
      <br>
      <br>
      <br>
      <br>
    </ul>
  </div>
</nav>

<body>
  {% block content %}
  {% endblock %}
</body>
<footer>
    <div class="footer-section">
      <div class="button">
      <a href="{{ url_for('information') }}"> <h3>Healthy Ageing Plans</h3><h3>Disclaimer</h3></a>
        </div>
    </div>

    <div class="footer-section">
      <div class="button">
      <a href="mailto:healthyageinghub24@gmail.com" target="_blank"><h3>Contact us</h3>
      <p>Email: healthyageinghub24@gmail.com</p>
        </a>
        </div>
    </div>

    <div class="footer-section">
      <h3>Follow us</h3>
      <a href="https://www.instagram.com/healthyageinghub24/" target="_blank"><img src="/static/resources/Instagram.svg"></a>
      <a href="https://twitter.com/HealthyAgeingHQ" target="_blank"><img src="/static/resources/X.svg"></a>
      <a href="https://www.facebook.com/profile.php?id=61557708340433" target="_blank"><img src="/static/resources/Facebook.svg"></a>
    </div>
</footer>
</html>